version: '3.9'
services:
  issuer:
    build: issuer
    ports:
      - '3003:3003'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  verifier:
    build: verifier
    ports:
      - '3004:3004'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
