import { Head, Html, Main, NextScript } from 'next/document';

import { BASE_PATH } from '@/utils/constants';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={`${BASE_PATH}/images/ssi_icon_b.png`} />
      </Head>
      <body className="bg-gradient min-h-screen">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
