import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Masca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/static/ssi_icon_b.png" />
      </Head>
      <body className="font-cabin min-h-screen bg-gradient">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
