name: 'Feature Request'
description: 'Request a new feature.'
title: '[feature](package): '
labels: ['feature']
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summary of the context why you want to do this.
      placeholder: "Add the P-256 curve support for EBSI. That way, the Snap can be used with issuer and verifier throughout EBSI's environment."
    validations:
      required: true
  - type: textarea
    id: story
    attributes:
      label: Expected behavior / User Story
      description: Describe how you expect this improvement to behave once in production.
      placeholder: When selecting `did:ebsi` method, I would like to select the curve used for generating keys.
    validations:
      required: false
