name: CRON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    name: Nx Cloud - Cron Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      pnpm-version: 8.9.2
      node-version: 18.18.2
      number-of-agents: 2
      main-branch-name: 'develop'
      parallel-commands-on-agents: |
        pnpm exec nx run-many --target=test:cron --parallel=2

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 2
      pnpm-version: 8.9.2
      node-version: 18.18.2
