name: Dapp deploy/build action

on:
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/dapp/**'
      - 'Dockerfile'
  push:
    branches: [master, develop]
    paths:
      - 'packages/dapp/**'
      - 'Dockerfile'

jobs:
  test-build:
    # Test build on every PR to DEVELOP
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm nx run @blockchain-lab-um/dapp:lint
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Test build dapp
        run: pnpm nx run @blockchain-lab-um/dapp:build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

  test-deploy:
    # Test deploy when we PUSH to DEVELOP
    if: ${{ (github.ref == 'refs/heads/develop') && (github.event_name == 'push') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create nx-cloud.env
        run: echo "NX_CLOUD_ACCESS_TOKEN=$NX_CLOUD_ACCESS_TOKEN" > nx-cloud.env
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Build blockchain-lab-um/ssi-snap
        run: docker build . -t blockchain-lab-um/ssi-snap
      - name: Build blockchain-lab-um/dapp
        run: docker build ./packages/dapp -t blockchain-lab-um/dapp
      - name: Change image tag
        run: docker tag blockchain-lab-um/dapp:latest bclabum.informatika.uni-mb.si/registry/dapp:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: bclabum.informatika.uni-mb.si/registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to private docker registry
        run: docker push bclabum.informatika.uni-mb.si/registry/dapp:latest
  deploy:
    # Deploy only when we PUSH to MASTER
    if: ${{ (github.ref == 'refs/heads/master') && (github.event_name == 'push') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'develop'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm nx run @blockchain-lab-um/dapp:lint
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Test build dapp
        run: pnpm nx run @blockchain-lab-um/dapp:build
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/dapp/.next
