name: Sync fork

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.FORK_KEY }}
      - name: Push to fork repo
        env:
          USE_SSH: true
        run: |
          git remote add fork git@github.com:bclabum/masca.git
          git config --global user.email "blockchain-lab@um.si"
          git config --global user.name "blockchain-lab"
          git push fork --force
